### ISSUE TITLE
Error codes on NSX (e.g. 400, 500) should throw an exception instead of SystemExit

### ISSUE THREAD

**Issue by yfauser** [vmware/nsxramlclient#13]
Currently nsxramlclient wil use SystemExit if a non successful status code like 400 or 500 is received from NSX (actually everything that is not in 200, 201 or 204).
Instead of using SystemExit we should define an exception and pass the error received from NSX into the Exception.

In the mean time one can catch non successful exits by using the following try/except block:

try:
       ------
       -----
except SystemExit as e:

      -----

**Comment by Asayu123** [comment]
Hi, I'm a user of your nice library and I was just about to post the same problem.(with version 2.0.3)

In my opinion, raise Error is one of nice option, but another solution is to simply return OrderedDict same as the success response in http_session.py .

It can be achieved by just escaping line-109 with small fix in line-103 (by calling 'xml_to_dict(et.fromstring(response.content))' instead of 'pretty_xml(response.content)').

Then, user can handle http error by referring OrderedDict's 'status'. 

If you prefer, i can send pull request that modify error handling like above.
I'm looking forward your response. Thank you in advance.

**Comment by yfauser** [comment]
Hi @Asayu123 .... sorry that I'm late replying. I was really busy traveling. and now I have a pile of things to work on. I like your idea! The only problem I see is the dependence on exiting for existing code (e.g. nsxansible, pynsxv, ...). 
Can I suggest an option when Instantiating the client Object? With a default being sysexit, and other options being raise and continue (and pass the HTTP status code as you suggest).
What do you think?

**Comment by Asayu123** [comment]
Hi @yfauser , I am glad you are safe!  
> Can I suggest an option when Instantiating the client Object? With a default being sysexit, and other options being raise and continue (and pass the HTTP status code as you suggest).  

I think it's a great idea because it gives both compatibility and flexibility. I like it !

**Comment by yfauser** [comment]
Hi @Asayu123, I added the 'raise' and 'continue' option to nsxramlclient into the devel branch. You can look at the last 3 commits referencing this issue for details.

Can you test in your environment, and see if the new code works for you and is according to your expectation? 

If it works for you I will merge the new Version into master.

You can download the 2.0.4 tarbal from the /dist folder and install it using 'pip install nsxramlclient....tar.gz'

Thanks!

**Comment by Asayu123** [comment]
Hi @yfauser , I tested your commit and I found it works perfect for me !  

I believe that both new option will make this library much easier to handle.
Thank you for taking time out of your busy schedule.
